### ISSUE TITLE
Add the license used to distribute the models

### ISSUE THREAD

**Issue by AlexisDrogoul** [COMOKIT/CoVid19#17]
We should make it clear which license we use to share and distribute these models.

**Comment by RoiArthurB** [comment]
Well it mostly depend on how we do want it to be used : 
- If we want it to keep any use-case open source, we should prefer a strong license like _GPL_ (but I'm not sure if it can be used for a toolkit like COMOKIT)
- If we want to keep any modification open source, but not the applications, we can use a license like _LGPL_
- If we just want to protect us (from if it's not working or anything else), we can use a weak license like _MIT_ 

I think the _LGPL_ would be better because, in some cases, data won't be open so it will allow people to apply COMOKIT and protect their data but help to improve the project if they want to modify the code.
